/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApexChart: typeof import('./src/components/wrappers/ApexChart.vue')['default']
    AuthLogo: typeof import('./src/components/AuthLogo.vue')['default']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCardFooter: typeof import('bootstrap-vue-next/components/BCard')['BCardFooter']
    BCardHeader: typeof import('bootstrap-vue-next/components/BCard')['BCardHeader']
    BCardTitle: typeof import('bootstrap-vue-next/components/BCard')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownDivider']
    BDropdownHeader: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownHeader']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormFloatingLabel: typeof import('bootstrap-vue-next/components/BForm')['BFormFloatingLabel']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BOffcanvas: typeof import('bootstrap-vue-next/components/BOffcanvas')['BOffcanvas']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BTable: typeof import('bootstrap-vue-next/components/BTable')['BTable']
    CardWithAction: typeof import('./src/components/CardWithAction.vue')['default']
    ChartJs: typeof import('./src/components/wrappers/ChartJs.vue')['default']
    ChoicesInput: typeof import('./src/components/ChoicesInput.vue')['default']
    ChoicesSelect: typeof import('./src/components/ChoicesSelect.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    EChart: typeof import('./src/components/wrappers/EChart.vue')['default']
    FileUploader: typeof import('./src/components/FileUploader.vue')['default']
    Icon: typeof import('./src/components/wrappers/Icon.vue')['default']
    JsVectorMap: typeof import('./src/components/JsVectorMap.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    MultiSelect: typeof import('./src/components/MultiSelect.vue')['default']
    PageBreadcrumb: typeof import('./src/components/PageBreadcrumb.vue')['default']
    PasswordStrengthBar: typeof import('./src/components/PasswordStrengthBar.vue')['default']
    Rating: typeof import('./src/components/Rating.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TablePagination: typeof import('./src/components/TablePagination.vue')['default']
    TouchSpinInput: typeof import('./src/components/TouchSpinInput.vue')['default']
  }
}
