version: '3'
services:
  genesiis-admin:
    build: .
    container_name: genesiis-admin
    ports:
      - '9007:9007'
    volumes:
      - .:/home/node/app:rw
    restart: 'no'
    command: sh
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
